elan:
  types: ['Controller', 'Pad']
enerchi:
  types: ['HandUnit']
vivid:
  types: ['Controller', 'Accessory', 'Paddle']
luxana:
  types: ['Unit', 'Light Bed', 'Sauna']
educator:
  types: ['Control Box', 'Leather harness', 'Rubber strap']
arciplex:
  types: ['Invention', 'Design', 'Innovation', 'Prototype', 'Sample']
portervision:
  types: ['Headset']
vesna:
  types: ['Unit']
luminis:
  types: ['Light bed', 'Light bulb']
arciplex_demo:
  types: ['Invention', 'Design', 'Innovation', 'Prototype', 'Sample']
