development:
  host: localhost
  adapter: postgresql
  database: arciplex_development

production:
  adapter: postgresql
  database: arciplex_production

staging:
  adapter: postgresql
  database: arciplex_staging

test:
  host: localhost
  adapter: postgresql
  database: arciplex_test
