development:
  host: localhost
  adapter: postgresql
  database: arciplex_development

production:
  adapter: postgresql
  database: arciplex_production

test:
  host: localhost
  adapter: postgresql
  database: arciplex_test