vesna:
    service_requests: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Warranty+Service+Requests+via+Client+Innovator+Website+.pdf"
    orders: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Drop+Ship+Order.pdf"
portervision:
    service_requests: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Warranty+Service+Requests.pdf"
luminis:
    orders: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Drop+Ship+Order.pdf"
    service_requests: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Warranty+Service+Requests+via+Client+Innovator+Website+.pdf"
vivid:
    service_requests: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Warranty+Service+Requests+via+Client+Innovator+Website+.pdf"
    orders: "ARCiPLEX+Back+Office+User+Guide+–+Client+Innovator+Drop+Ship+Order.pdf"
